apiVersion: v1
kind: Service
metadata:
  name: flask-service-3
spec:
  selector:
    app: flask-app-3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  # or NodePort, depending on your setup
