apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv-4
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc-3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
