version: '3'
services:
    my-app:
        image: <image-url-from-private-regustry(GCR)>
        ports:
            - 3000:3000
    mongodb:   
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=password
    mongo-express:
        image: mongo-express
        ports:
            - 8080:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password 
            - ME_CONFIG_MONGODB_SERVER=mongodb