apiVersion: v1
kind: Pod
metadata:
  name: panda-pod
  labels:
    app: panda
    type: kodekloud
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        request:
          memory: "1Gi"
          cpu: 1
        limits:
          memory: "2Gi"
          cpu: 2
  nodeName: controlplane # schdule this Pod on this Node
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"
    