apiVersion: v1
kind: Pod
metadata:
  name: panda-pod
  labels:
    app: panda
    type: kodekloud
spec:
  containers:
    - name: nginx-container
      image: nginx
  nodeName: controlplane # schdule this Pod on this Node

  tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"
    