apiVersion: v1
kind: ReplicationController
metadata: # metadata of rc
  name: panda-rc
  labels:
    app: panda
    type: kodekloud
spec:
  template:
    metadata: # metadata of Pod
      name: panda-pod
      labels:
        app: panda
        type: kodekloud
    spec: # Pod Spec
      containers:
      - name: nginx-container
        image: nginx
        
  replicas: 2