apiVersion: v1
kind: Service
metadata:
  app: panda-np-svc
  type: kodekloud
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80 
    nodePort: 30008
  selector:
    app: panda-pod
    type: kodekloud