apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-first-replicaset
  env: development
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
  selector:
    matchLabels:
      name: nginx # should match with the label provided in pod definition
