apiVersion: v1
kind: ReplicationController
metadata:
  name: my-first-rcontroller
  env: development
spec:
  replicas: 3
  selector:
    app: my-first-rcontroller
  template:
    metadata:
      name: my-first-rcontroller
      labels:
        app: my-first-rcontroller
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
