apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod
  labels:
    name: nginx
    type: webserver
    env: development
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
